name: "Algolia Docsearch Indexer"
description: "Update an Algolia Docsearch index"
branding:
  icon: "book"
  color: "blue"
inputs:
  APPLICATION_ID:
    description: "Algolia docsearch APPLICATION_ID"
    required: true
  ADMIN_API_KEY:
    description: "Algolia docsearch API_KEY"
    required: true
  FILE_PATH:
    description: "File path to docsearch"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.FILE_PATH }}
    - ${{ inputs.INDEX_NAME }}
    - ${{ inputs.APPLICATION_ID }}
    - ${{ inputs.ADMIN_API_KEY }}
